config/routes.rb
Rails.application.routes.draw do

  root 'shelters#index'
  
  resources :shelters do
    resources :clients
    resources :animals do
    	get 'adopt' => "animals#adopt"
     	put 'complete_adoption' => "animals#complete_adoption"
    end
end
    resources :clients do
		resources :animals do
		get 'donate' => "animals#donate"
		put 'complete_donation' => "animals#complete_donation"
	end
  end
  
  resources :animals
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :shelter
  belongs_to :client
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :shelter
  has_many :animals
end

app/models/shelter.rb
class Shelter < ActiveRecord::Base
	has_many :clients
	has_many :animals
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

	def show
		@animal = Animal.find(params[:id])
		@shelter = Shelter.find(2)
		@client = @animal.client_id


	end

	def new
		@shelter = Shelter.find(params[:shelter_id])
		@animal = @shelter.animals.new
	end

	def create
		@shelter = Shelter.find(params[:shelter_id])
		@animal = @shelter.animals.new(safe_animal_params)
		if @animal.save
			flash[:notice] = "Animal has been added!"
			redirect_to shelter_path(@shelter)
		else
			flash[:notice] = "Error!"
			render :new
		end
	end

	def adopt
		@animal = Animal.find(params[:id])
		@shelter = Shelter.find(2)
		@clients = @shelter.clients

	end

	def complete_adoption
		@shelter = Shelter.find(2)
		@animal = Animal.find(params[:id])
		@animal.shelter_id = nil
		@animal.client_id = params[:client]
		@animal.save
		redirect_to shelter_path(@shelter)
	end

	def donate
		@animal = Animal.find(params[:animal_id])
		@client = @animal.client_id
		@shelter = Shelter.find(2)
	end

	def complete_donation
		@shelter = Shelter.find(2)
		@client = @animal.client_id
		@animal = Animal.find(params[:animal_id])
		@animal.client_id = nil
		@animal.shelter_id = params[:shelter]
		@animal.save
		redirect_to shelter_path(@shelter)
	end


	private

	def safe_animal_params
		params.require(:animal).permit(:name, :species, :photo, :client_id)
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

	def show

		@client = Client.find(params[:id])
		@shelter = Shelter.find((2))
		@pets = @client.animals

	end

	def new
		@shelter = Shelter.find(2)
		@client = @shelter.clients.new

	end

	def create
		@shelter = Shelter.find(2)
		@client = @shelter.clients.new(safe_client_params)
		if @client.save
			flash[:notice] = "Client has been added!"
			redirect_to shelter_path(@shelter)
		else
			flash[:notice] = "Error!"
			render :new
		end
	end



	private

	def safe_client_params
		params.require(:client).permit(:name, :age, :photo)
	end

end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController

	def index
		@shelters = Shelter.all
	end

	def show
		@shelter = Shelter.find(params[:id])
		@animals = @shelter.animals
		@clients = @shelter.clients
	end

	




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/adopt.html.erb
<h1>Adopt <%=@animal.name%></h1>

Select a client to adopt <%=@animal.name%> 


	<%= form_tag(shelter_animal_complete_adoption_path, method: 'put') do %>
	<p> 
		Who is adopting <%= @animal.name %>? 
		<%= select_tag('client', options_from_collection_for_select(@clients, "id", "name")) %>
		<%= submit_tag 'submit' %>
	</p>
<% end %>


	


	

app/views/animals/donate.html.erb
<h1>Donate <%=@animal.name%></h1>

Select a shelter to donate <%=@animal.name%> 


	<%= form_tag(client_animal_complete_donation_path, method: 'put') do %>
	<p> 
		Donate <%= @animal.name %> to 
		<%= select_tag('shelter', options_from_collection_for_select(@shelter, "id", "name")) %>
		<%= submit_tag 'submit' %>
	</p>
<% end %>

app/views/animals/new.html.erb
<%= form_for @animal do |a| %>

	<p> NAME: <%=a.text_field :name%></p>
	<p> SPECIES: <%=a.text_field :species%></p>
	<p> PHOTO: <%=a.text_field :photo%></p>

	<p><%=a.submit%></p>

	<%end%>

app/views/animals/show.html.erb
<h1><%=@animal.name%></h1>

<p><img src= <%=@animal.photo%>> </p>

<p><%=link_to "Adopt #{@animal.name}!", shelter_animal_adopt_path(@shelter, @animal)%></p>

<p><%=link_to "Donate #{@animal.name}", client_animal_donate_path(@client, @animal)%></p>


<p><%=link_to "Back to #{@shelter.name}", shelter_path(@shelter)%></p>

app/views/clients/new.html.erb
<%= form_for @client do |c| %>

	<p> NAME: <%=c.text_field :name%></p>
	<p> AGE: <%=c.text_field :age%></p>
	<p> PHOTO: <%=c.text_field :photo%></p>

	<p><%=c.submit%></p>

	<%end%>

app/views/clients/show.html.erb
<h1><%=@client.name%></h1>

<p><img src= <%=@client.photo%> height=300> </p>

<p><h3>Shelter: <%=link_to @shelter.name, shelter_path(@shelter)%></h3></p>

<p><h3> Pets:</h3></p>

<ul><%@pets.each do |p|%>

<p><li><img src = <%=p.photo%> height= 300></li></p>
<p><%=link_to p.name, p%></p>

<%end%></ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Happitails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shelters/index.html.erb
<% @shelters.each do |s|%>

<%= link_to s.name, s%>

<%end%>

app/views/shelters/show.html.erb
<h1> Welcome to Happitails!</h1>

<%=link_to "Add an Animal", new_shelter_animal_path(@shelter)%> | 
<%=link_to "Add a Client", new_shelter_client_path(@shelter)%> | 


<h2> Animals Available for Adoption </h2>
	
	<ul> <%@animals.each do |s|%>

	<li><%=link_to s.name, shelter_animal_path(@shelter, s)%></li>
		
	<%end%></ul>


<h2> Clients </h2>

	<ul> <%@clients.each do |c|%>
	<li> <%=link_to c.name, shelter_client_path(@shelter, c)%></li>
	<%end%></ul>